FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

WORKDIR /app

# Copy everything else and build
COPY . ./
RUN dotnet publish src/{{PROJECT_NAME}} -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# Copy binary
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "{{PROJECT_NAME}}.dll"]